"""
Initial migration

Revision ID: c887c5e24e6e
Revises: 
Create Date: 2026-04-27 00:04:53.628000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c887c5e24e6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('excel_template_path', sa.String(length=500), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'TECNICO', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('instrument_tag', sa.String(length=255), nullable=True),
    sa.Column('instrument_description', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('range_min', sa.String(length=100), nullable=True),
    sa.Column('range_max', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'QUEUED', 'PROCESSING', 'DONE', 'ERROR', name='certificate_status'), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('calibration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_certificates_created_by', 'certificates', ['created_by'], unique=False)
    op.create_index('idx_certificates_status', 'certificates', ['status'], unique=False)
    op.create_index('idx_certificates_template', 'certificates', ['template_id'], unique=False)
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_table('template_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'SELECT', 'TEXTAREA', name='field_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excel_cell_ref', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_fields_template_id'), 'template_fields', ['template_id'], unique=False)
    op.create_table('certificate_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('certificate_id', sa.Uuid(), nullable=False),
    sa.Column('point_number', sa.Integer(), nullable=False),
    sa.Column('nominal_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('measured_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('error_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('uncertainty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('excel_row_ref', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_points_certificate_id'), 'certificate_points', ['certificate_id'], unique=False)
    op.create_table('processing_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('certificate_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'ERROR', name='queue_status'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id')
    )
    op.create_index('idx_queue_status_created', 'processing_queue', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_queue_status_created', table_name='processing_queue')
    op.drop_table('processing_queue')
    op.drop_index(op.f('ix_certificate_points_certificate_id'), table_name='certificate_points')
    op.drop_table('certificate_points')
    op.drop_index(op.f('ix_template_fields_template_id'), table_name='template_fields')
    op.drop_table('template_fields')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_index('idx_certificates_template', table_name='certificates')
    op.drop_index('idx_certificates_status', table_name='certificates')
    op.drop_index('idx_certificates_created_by', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('templates')
    # ### end Alembic commands ###
